apiVersion: v2
name: pagopa-stand-in-tech-support
description: Microservice that handles Stand-In tech support api
type: application
version: 0.69.0
appVersion: 0.0.10
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
